[build]
  command = "flutter build web"               
  publish = "build/web"

           

[dev]
  command = "flutter run"                    
  port = 3000                                   

[context.production.environment]
  CLOUDINARY_CLOUD_NAME = ""                    
  GEMINI_API_KEY = ""                          
  GOOGLE_API_KEY = ""                           
  GOOGLE_CUSTOM_SEARCH_API_KEY = ""             
  GOOGLE_GEMINI_API_KEY = ""                    
  MONGODB_API_KEY = ""                         
  MONGODB_EDGE_SERVER_TOKEN = ""                
  # Add any other environment variables you need here

[[plugins]]
  package = "@netlify/plugin-nextjs"             

# Uncomment and add any other desired plugins as needed
# [[plugins]]
#   package = "netlify-plugin-
# [[plugins]]
#   package = "netlify-plugin-amp-server-side-rendering" 
# [[plugins]]
#   package = "netlify-plugin-html-validate"    
# [[plugins]]
#   package = "netlify-plugin-inline-critical-css" 
# [[plugins]]
#   package = "netlify-plugin-image-optim"       
# [[plugins]]
#   package = "netlify-plugin-inline-source" 
