[build]
  command = "flutter build web"              # Command to build your Flutter web app
  publish = "build/web"                      # Directory for the built Flutter web app

[dev]
  command = "flutter run"                     # Optional: Command for local development
  port = 3000                                  # Optional: Local development port

[functions]
  directory = "netlify/functions"             # Adjust if you have serverless functions

[context.production.environment]
  CLOUDINARY_CLOUD_NAME = ""                  # Set your Cloudinary cloud name
  GEMINI_API_KEY = ""                         # Set your Gemini API key
  GOOGLE_API_KEY = ""                          # Set your Google API key
  GOOGLE_CUSTOM_SEARCH_API_KEY = ""           # Set your Google custom search API key
  GOOGLE_GEMINI_API_KEY = ""                  # Set your Google Gemini API key
  MONGODB_API_KEY = ""                         # Set your MongoDB API key
  MONGODB_EDGE_SERVER_TOKEN = ""               # Set your MongoDB edge server token
  # Add any other environment variables you need here

[[plugins]]
  package = "@netlify/plugin-nextjs"         
  # Uncomment and add your desired plugins as needed
  # package = "netlify-plugin-cloudinary"
  # package = "netlify-plugin-amp-server-side-rendering"
  # package = "netlify-plugin-html-validate"
  # package = "netlify-plugin-inline-critical-css"
  # package = "netlify-plugin-inline-functions-env"
  # package = "netlify-plugin-image-optim"
  # package = "netlify-plugin-inline-source"

 




